
-- 3 Created table

DROP DATABASE IF EXISTS burgers_db;
CREATE DATABASE burgers_db;

USE burgers_db;


CREATE TABLE burgers (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY
burger_name VARCHAR (30) UNIQUE NOT NULL
PRIMARY KEY (id),
);