-- db BURGER
DROP DATABASE IF EXISTS burgers_db;
CREATE DATABASE burgers_db;

USE burgers_db;

-- BURGER TABLE
CREATE TABLE burgers (
id INT NOT NULL AUTO_INCREMENT,
burger_name VARCHAR (30) NOT NULL,
devoured  BOOLEAN NOT NULL
PRIMARY KEY (id)
);